### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by maxbauer** [medDV-GmbH/ngx-pinch-zoom#18]
At first thanks for the updated fork :)

Installing the package does not work the way described in the readme.
This worked for me:

> npm install --save https://github.com/medDV-GmbH/ngx-pinch-zoom

**Comment by Raysix93** [comment]
This should do the trick as well since we publish this package on npmjs.

`npm i @meddv/ngx-pinch-zoom`

I will update the readme shortly.
