### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by dtarnawsky** [medDV-GmbH/ngx-pinch-zoom#31]
I'm hoping that Angular 17 support is on the radar! At the moment [Angular 16 is a peer dependency](https://github.com/medDV-GmbH/ngx-pinch-zoom/blob/fb46fa400c3b65cbb5f449ce98d522d45076e17a/projects/ngx-pinch-zoom/package.json#L38).

**Comment by Raysix93** [comment]
I'll publish a new Version as soon as our mail system is out of maintenance. Can't login to npmjs right now, due to 2FA.

**Comment by Raysix93** [comment]
Update published

**Comment by dtarnawsky** [comment]
Awesome! Thanks so much - your work is very much appreciated!
