### ISSUE TITLE
Add support for reset zoom

### ISSUE THREAD

**Issue by btm-mbas** [medDV-GmbH/ngx-pinch-zoom#32]
Please add support for resetting zoom scale. Thanks

**Comment by Raysix93** [comment]
toggleZoom() should reset the scale if you have zoomed in.

**Comment by Raysix93** [comment]
Closing due Inactivity

**Comment by kinggolf** [comment]
@Raysix93 toggleZoom() works well, but what is the best way to know if the element has been zoomed? If call toggleZoom() and there is no zoom, then we go to max zoom.

**Comment by kinggolf** [comment]
Looks like `isZoomedIn` does the job.
