### ISSUE TITLE
Can't bind to XXX since it isn't a known property of 'pinch-zoom'

### ISSUE THREAD

**Issue by aliyafthh** [medDV-GmbH/ngx-pinch-zoom#39]
Hi, I am trying to set the properties value but it says it's an unknown property. Mind checking into this?
<img width="286" alt="Screenshot 2024-02-21 at 11 10 03 AM" src="https://github.com/medDV-GmbH/ngx-pinch-zoom/assets/52777962/0babab9d-ba3c-49df-ba7c-5649214f9a3f">

**Comment by Raysix93** [comment]
Did you import the module?

**Comment by aliyafthh** [comment]
Yes, I did. I am able to use the plugin, just getting error when i try to set properties. Only when i add the NO_ERRORS_SCHEMA then I'm able to set.

**Comment by Raysix93** [comment]
Normally that happens if the Module isn't imported the right way. Are you able to share more of your code and the error messages? Are you using Standalone Components?

**Comment by aliyafthh** [comment]
I'm also not sure why im getting this error. No, I am not using standalone components . But here are some screenshots of my code
<img width="393" alt="Screenshot 2024-02-21 at 7 58 20 PM" src="https://github.com/medDV-GmbH/ngx-pinch-zoom/assets/52777962/c7d047cc-eb69-4206-a2f6-fa576391fae2">
<img width="1139" alt="Screenshot 2024-02-21 at 7 57 37 PM" src="https://github.com/medDV-GmbH/ngx-pinch-zoom/assets/52777962/8fa44e66-f097-4280-8c87-e5a9bdbdd798">
<img width="789" alt="Screenshot 2024-02-21 at 7 57 52 PM" src="https://github.com/medDV-GmbH/ngx-pinch-zoom/assets/52777962/7f9c1ee4-c3b1-4db8-b9f9-cfb2dc2f9e15">

**Comment by aliyafthh** [comment]
Yes, that seems to be the fix. Thank you!
