### ISSUE TITLE
limitZoom feature seems to be not working.

### ISSUE THREAD

**Issue by vijaymsit88** [medDV-GmbH/ngx-pinch-zoom#41]
Thank you so much for this utility!! 

I am facing one issue while using it with Angular version 16.2.11. I am using it like below, the limit Zoom property does not seem to be working. 
`  <pinch-zoom limit-zoom="2500">
 <canvas> </canvas>
 </pinch-zoom>`

I have a highly detailed image with a very high resolution (opening within HTML Canvas) and one can easily zoom in using a mouse scroll in my web app. However, when opening within a tablet device and doing a pinch zoom with this library, I am only able to zoom in to the scale of 3 (which seems like default behaviour).

I want to be able to pinch and zoom to 2500%. Some help will be appreciated.

**Comment by Raysix93** [comment]
Hello there,

this has been fixed in PR #33 and is already released in version 17.0.1. on NPM. If you want to use the newest version you will have to upgrade Angular. If the error still remains after using the newest version please let me know.

**Comment by vijaymsit88** [comment]
Thanks for answering. Should I be using it like- limit-zoom="2500"    or      [limitZoom]="2500"   or limitZoom="2500"
Not sure what should be the correct syntax here.

**Comment by Raysix93** [comment]
limit-zoom for static value or [limit-zoom] depending on if you need to change the Value. Its standard Angular binding.

**Comment by vijaymsit88** [comment]
Actually, within the code, it's mentioned limit-zoom for backward compatibility and limitZoom for the new version....so that created some confusion. Thanks for the quick response. You may close this issue.

**Comment by Raysix93** [comment]
Ohh yeah you're right, I see that now. Sorry we didn't use this feature yet and I didn't know. You can try out both. If you have any issues with it you can re-open this issue. Thank you :)
